package EpnRemoto;


/**
* EpnRemoto/EpnRemHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EpnRemoto.idl
* lunes 8 de enero de 2018 16:46:52 Hora de Colombia
*/

abstract public class EpnRemHelper
{
  private static String  _id = "IDL:EpnRemoto/EpnRem:1.0";

  public static void insert (org.omg.CORBA.Any a, EpnRemoto.EpnRem that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EpnRemoto.EpnRem extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (EpnRemoto.EpnRemHelper.id (), "EpnRem");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EpnRemoto.EpnRem read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EpnRemStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EpnRemoto.EpnRem value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static EpnRemoto.EpnRem narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EpnRemoto.EpnRem)
      return (EpnRemoto.EpnRem)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EpnRemoto._EpnRemStub stub = new EpnRemoto._EpnRemStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static EpnRemoto.EpnRem unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EpnRemoto.EpnRem)
      return (EpnRemoto.EpnRem)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EpnRemoto._EpnRemStub stub = new EpnRemoto._EpnRemStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
