package EpnRemoto;


/**
* EpnRemoto/EpnRem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EpnRemoto.idl
* lunes 8 de enero de 2018 16:46:52 Hora de Colombia
*/

public interface EpnRem extends EpnRemOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EpnRem
